### docker-compose.yml ###
## Access the jupyterlab instance at:
## https://${HOSTNAME}:8081/tanspaces.${COMPOSE_PROJECT_NAME}/lab

services:
  workspace:
    extends:
      file: ${JUPYTER_SERVICE}
      service: jupyter

networks:
  tanspaces:
    external: true
